name: Build and Push Docker Image to AWS ECR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          docker build -t 084375568856.dkr.ecr.eu-north-1.amazonaws.com/wisecow:${{ github.sha }} .

      - name: Push Docker image to Amazon ECR
        run: |
          docker push 084375568856.dkr.ecr.eu-north-1.amazonaws.com/wisecow:${{ github.sha }}
