name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Ensure server.key exists
        run: |
          mkdir -p $HOME/wisecow-app1
          echo "" > $HOME/wisecow-app1/server.key

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: your-docker-image-name:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Kubeconfig
        run: echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
